language: php

php:
  - 7.0
  - 5.4
  - 5.5
  - 5.6


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
