language: php

php:
  - 7.0
  - 5.5
  - 5.6

dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: 7.0
before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
